// <auto-generated />
using CadastroPrograma.Contexto;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CadastroPrograma.Migrations
{
    [DbContext(typeof(CadastroContext))]
    [Migration("20210406231705_PrimeiroUp")]
    partial class PrimeiroUp
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.5")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("CadastroPrograma.Models.Habilidades", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Android")
                        .HasColumnType("int");

                    b.Property<int>("Angular")
                        .HasColumnType("int");

                    b.Property<int>("AngularJs1")
                        .HasColumnType("int");

                    b.Property<int>("AspMvc")
                        .HasColumnType("int");

                    b.Property<int>("AspWebForm")
                        .HasColumnType("int");

                    b.Property<int>("Bootstrap")
                        .HasColumnType("int");

                    b.Property<int>("C")
                        .HasColumnType("int");

                    b.Property<int>("Cake")
                        .HasColumnType("int");

                    b.Property<int>("Csharp")
                        .HasColumnType("int");

                    b.Property<int>("Css")
                        .HasColumnType("int");

                    b.Property<int>("Djanto")
                        .HasColumnType("int");

                    b.Property<int>("ExpressNode")
                        .HasColumnType("int");

                    b.Property<int>("Flutter")
                        .HasColumnType("int");

                    b.Property<int>("Html")
                        .HasColumnType("int");

                    b.Property<int>("Ilustrator")
                        .HasColumnType("int");

                    b.Property<int>("InfoProgramadorId")
                        .HasColumnType("int");

                    b.Property<int>("Ionic")
                        .HasColumnType("int");

                    b.Property<int>("Ios")
                        .HasColumnType("int");

                    b.Property<int>("Java")
                        .HasColumnType("int");

                    b.Property<int>("Jquery")
                        .HasColumnType("int");

                    b.Property<int>("Laravel")
                        .HasColumnType("int");

                    b.Property<int>("Majento")
                        .HasColumnType("int");

                    b.Property<int>("MySql")
                        .HasColumnType("int");

                    b.Property<int>("MySqlServer")
                        .HasColumnType("int");

                    b.Property<int>("NodeJS")
                        .HasColumnType("int");

                    b.Property<string>("Outros")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("Photoshop")
                        .HasColumnType("int");

                    b.Property<int>("Php")
                        .HasColumnType("int");

                    b.Property<int>("Python")
                        .HasColumnType("int");

                    b.Property<int>("ReactJS")
                        .HasColumnType("int");

                    b.Property<int>("ReactNative")
                        .HasColumnType("int");

                    b.Property<int>("Ruby")
                        .HasColumnType("int");

                    b.Property<int>("Salesforce")
                        .HasColumnType("int");

                    b.Property<int>("Seo")
                        .HasColumnType("int");

                    b.Property<int>("Swift")
                        .HasColumnType("int");

                    b.Property<int>("Vue")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("InfoProgramadorId");

                    b.ToTable("Habilidades");
                });

            modelBuilder.Entity("CadastroPrograma.Models.InfoProgramador", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.Property<bool>("HorarioComercial")
                        .HasColumnType("bit");

                    b.Property<bool>("HorarioMadrugada")
                        .HasColumnType("bit");

                    b.Property<bool>("HorarioManha")
                        .HasColumnType("bit");

                    b.Property<bool>("HorarioNoite")
                        .HasColumnType("bit");

                    b.Property<bool>("HorarioTarde")
                        .HasColumnType("bit");

                    b.Property<string>("Linkedin")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Local")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("NumeroWhats")
                        .HasMaxLength(21)
                        .HasColumnType("int");

                    b.Property<string>("Portifolio")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Salario")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("InfoProgramador");
                });

            modelBuilder.Entity("CadastroPrograma.Models.Habilidades", b =>
                {
                    b.HasOne("CadastroPrograma.Models.InfoProgramador", "InfoProgramador")
                        .WithMany()
                        .HasForeignKey("InfoProgramadorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("InfoProgramador");
                });
#pragma warning restore 612, 618
        }
    }
}
